xcopy argmatch.h \projects\cpp\include
xcopy backupfile.h \projects\cpp\include
xcopy error.h \projects\cpp\include
xcopy fnmatch.h \projects\cpp\include
xcopy fsusage.h \projects\cpp\include
xcopy getdate.h \projects\cpp\include
xcopy getline.h \projects\cpp\include
xcopy getopt.h \projects\cpp\include
xcopy group-member.h \projects\cpp\include
xcopy long-options.h \projects\cpp\include
xcopy makepath.h \projects\cpp\include
xcopy modechange.h \projects\cpp\include
xcopy mountlist.h \projects\cpp\include
xcopy obstack.h \projects\cpp\include
xcopy path-concat.h \projects\cpp\include
xcopy pathmax.h \projects\cpp\include
xcopy regex.h \projects\cpp\include
xcopy rx.h \projects\cpp\include
xcopy save-cwd.h \projects\cpp\include
xcopy xstrtol.h \projects\cpp\include
xcopy xstrtoul.h \projects\cpp\include
