.TH DIRCOLORS 1L \" -*- nroff -*-
.SH NAME
dircolors \- output commands to set the LS_COLOR environment variable
.SH SYNOPSIS
.TP
\fBeval `dircolors\fR [\-b] [\-\-sh] [\-c] [\-\-csh] [\-\-help]
[\-\-version] [file]\fB`\fR
.SH DESCRIPTION
This documentation is no longer being maintained and may be inaccurate
or incomplete.  The Texinfo documentation is now the authoritative source.
