/* Automatically generated by po2tbl.sed from jwhois.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"invalid expire time", 2},
  {"using defaults", 3},
  {"unable to open", 4},
  {"disabling cache", 5},
  {"unable to store data in database", 6},
  {"host not found", 7},
  {"Address family for hostname not supported", 8},
  {"Temporary failure in name resolution", 9},
  {"Bad value for ai_flags", 10},
  {"Non-recoverable failure in name resolution", 11},
  {"ai_family not supported", 12},
  {"Memory allocation failure", 13},
  {"No address associated with hostname", 14},
  {"Name or service not known", 15},
  {"Servname not supported for ai_socktype", 16},
  {"ai_socktype not supported", 17},
  {"System error", 18},
  {"Unknown error", 19},
  {"Copyright (C) 1999  Free Software Foundation, Inc.", 20},
  {"\
This program is free software with ABSOLUTELY NO WARRANTY; you may\n\
redistribute it under the terms of the GNU General Public License.", 21},
  {"version", 22},
  {"Usage: jwhois [OPTIONS] [QUERY]", 23},
  {"\
  --version               display version number and patch level\n\
  --help                  display this help\n\
  -c FILE, --config=FILE  use FILE as configuration file\n\
  -h HOST, --host=HOST    explicitly query HOST\n\
  -p PORT, --port=PORT    use port number PORT (in conjunction with HOST)\n\
  -v, --verbose           verbose debug output\n", 24},
  {"\
  -f, --force-lookup      force lookup even if the entry is cached\n\
  -d, --disable-cache     disable cache functions\n", 25},
  {"Report bugs to bug-jwhois@gnu.org", 26},
  {"invalid port number", 27},
  {"error allocating memory", 28},
  {"string out of bounds on line", 29},
  {"end of file looking for '\"' on line", 30},
  {"unexpected end of file on line", 31},
  {"multiple keys on line", 32},
  {"missing key on line", 33},
  {"error creating socket", 34},
  {"fatal error searching for host to query", 35},
  {"fatal error reading cache", 36},
  {"cached", 37},
  {"error reading data from", 38},
  {"fatal error writing to cache", 39},
  {"invalid netmask on line", 40},
  {"redirected to", 41},
};

int _msg_tbl_length = 41;
