/* Automatically generated by po2tbl.sed from id-utils.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"can't allocate %ld bytes for hash table: memory exhausted", 2},
  {"Load=%ld/%ld=%.0f%%, ", 3},
  {"Rehash=%d, ", 4},
  {"Collisions=%ld/%ld=%.0f%%", 5},
  {"can't determine the io_size of a string!", 6},
  {"can't open `%s'", 7},
  {"`%s' is not an ID file! (bad magic #)", 8},
  {"`%s' is version %d, but I only grok version %d", 9},
  {"unsupported size in io_read (): %d", 10},
  {"unknown I/O type: %d", 11},
  {"unsupported size in io_write (): %d", 12},
  {"unrecognized language: `%s'", 13},
  {"can't allocate language args obstack: memory exhausted", 14},
  {"can't allocate language args: memory exhausted", 15},
  {"language name expected following `%s' in file `%s'", 16},
  {"can't open language map file `%s'", 17},
  {"can't get size of map file `%s'", 18},
  {"can't read language map file `%s'", 19},
  {"can't read entire language map file `%s'", 20},
  {"\
C language:\n\
  -k,--keep=CHARS        Allow CHARS in single-token strings, keep the \
result\n\
  -i,--ignore=CHARS      Allow CHARS in single-token strings, toss the \
result\n\
  -u,--strip-underscore  Strip a leading underscore from single-token \
strings\n", 21},
  {"junk: `%c'", 22},
  {"junk: `\\%03o'", 23},
  {"\
Assembly language:\n\
  -c,--comment=CHARS     Any of CHARS starts a comment until end-of-line\n\
  -k,--keep=CHARS        Allow CHARS in tokens, and keep the result\n\
  -i,--ignore=CHARS      Allow CHARS in tokens, and toss the result\n\
  -u,--strip-underscore  Strip a leading underscore from tokens\n\
  -n,--no-cpp            Don't handle C pre-processor directives\n", 24},
  {"\
Text language:\n\
  -i,--include=CHAR-CLASS  Treat characters of CHAR-CLASS as token \
constituents\n\
  -x,--exclude=CHAR-CLASS  Treat characters of CHAR-CLASS as token \
delimiters\n", 25},
  {"can't read directory `%s' (`.' from `%s')", 26},
  {"notice: `%s' was a %s, but is now a %s!", 27},
  {"file", 28},
  {"directory", 29},
  {"warning: `%s' and `%s' are the same file, but yield different scans!", 30},
  {"notice: scan parameters changed for `%s'", 31},
  {"can't get working directory", 32},
  {"can't chdir to `%s'", 33},
  {"can't chdir to `%s' from `%s'", 34},
  {"can't lstat `%s' from `%s'", 35},
  {"can't stat `%s' from `%s'", 36},
  {"%s: option `%s' is ambiguous\n", 37},
  {"%s: option `--%s' doesn't allow an argument\n", 38},
  {"%s: option `%c%s' doesn't allow an argument\n", 39},
  {"%s: option `%s' requires an argument\n", 40},
  {"%s: unrecognized option `--%s'\n", 41},
  {"%s: unrecognized option `%c%s'\n", 42},
  {"%s: illegal option -- %c\n", 43},
  {"%s: invalid option -- %c\n", 44},
  {"%s: option requires an argument -- %c\n", 45},
  {"Try `%s --help' for more information.\n", 46},
  {"Usage: %s [OPTION] FILENAME [FILENAME2]\n", 47},
  {"\
List identifiers that occur in FILENAME, or if FILENAME2 is\n\
also given list the identifiers that occur in both files.\n\
\n\
  -f, --file=FILE  file name of ID database\n\
      --help       display this help and exit\n\
      --version    output version information and exit\n", 48},
  {"no file name arguments", 49},
  {"too many file name arguments", 50},
  {"can't locate `ID'", 51},
  {"`%s' is ambiguous", 52},
  {"`%s' not found", 53},
  {"Usage: %s [OPTION]... [PATTERN]...\n", 54},
  {"\
Print constituent file names that match PATTERN,\n\
using shell-style wildcards.\n\
  -f, --file=FILE        file name of ID database\n\
  -S, --separator=STYLE  STYLE is one of `braces', `space' or `newline'\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n", 55},
  {"Usage: %s [OPTION]... PATTERN...\n", 56},
  {"\
Query ID database and report results.\n\
By default, output consists of multiple lines, each line containing the\n\
matched identifier followed by the list of file names in which it occurs.\n\
\n\
  -f, --file=FILE       file name of ID database\n\
\n\
  -i, --ignore-case     match PATTERN case insensitively\n\
  -l, --literal         match PATTERN as a literal string\n\
  -r, --regexp          match PATTERN as a regular expression\n\
  -w, --word            match PATTERN as a delimited word\n\
  -s, --substring       match PATTERN as a substring\n\
            Note: If PATTERN contains extended regular expression meta-\n\
            characters, it is interpreted as a regular expression \
substring.\n\
            Otherwise, PATTERN is interpreted as a literal word.\n\
\n\
  -k, --key=STYLE       STYLE is one of `token', `pattern' or `none'\n\
  -R, --result=STYLE    STYLE is one of `filenames', `grep', `edit' or \
`none'\n\
  -S, --separator=STYLE STYLE is one of `braces', `space' or `newline' and\n\
                        only applies to file names when \
`--result=filenames'\n\
            The above STYLE options control how query results are \
presented.\n\
            Defaults are --key=token --result=filenames --separator=%s\n\
\n\
  -F, --frequency=FREQ  find tokens that occur FREQ times, where FREQ\n\
                        is a range expressed as `N..M'.  If N is omitted, \
it\n\
                        defaults to 1, if M is omitted it defaults to \
MAX_USHRT\n\
  -a, --ambiguous=LEN   find tokens whose names are ambiguous for LEN chars\n\
\n\
  -x, --hex             only find numbers expressed as hexadecimal\n\
  -d, --decimal         only find numbers expressed as decimal\n\
  -o, --octal           only find numbers expressed as octal\n\
            By default, searches match numbers of any radix.\n\
\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n", 57},
  {"braces", 58},
  {"space", 59},
  {"notice: use of `-e' is deprecated, use `-r' instead", 60},
  {"All identifiers are non-ambiguous within the first %d characters\n", 61},
  {"invalid `--key' style: `%s'", 62},
  {"invalid `--result' style: `%s'", 63},
  {"edit? [y1-9^S/nq] ", 64},
  {"can't fork", 65},
  {"can't exec `%s'", 66},
  {"can't match regular-expression: memory exhausted", 67},
  {"Usage: %s [OPTION]... [FILE]...\n", 68},
  {"\
Build an identifier database.\n\
  -o, --output=OUTFILE    file name of ID database output\n\
  -f, --file=OUTFILE      synonym for --output\n\
  -i, --include=LANGS     include languages in LANGS (default: \"C C++ \
asm\")\n\
  -x, --exclude=LANGS     exclude languages in LANGS\n\
  -l, --lang-option=L:OPT pass OPT as a default for language L (see below)\n\
  -m, --lang-map=MAPFILE  use MAPFILE to map file names onto source \
language\n\
  -d, --default-lang=LANG make LANG the default source language\n\
  -p, --prune=NAMES       exclude the named files and/or directories\n\
  -v, --verbose           report per file statistics\n\
  -s, --statistics        report statistics at end of run\n\
\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n\
\n\
FILE may be a file name, or a directory name to recursively search.\n\
If no FILE is given, the current directory is searched by default.\n\
Note that the `--include' and `--exclude' options are mutually-exclusive.\n\
\n\
The following arguments apply to the language-specific scanners:\n", 69},
  {"can't create `%s' in `%s'", 70},
  {"can't modify `%s'", 71},
  {"can't stat `%s'", 72},
  {"  new = %d/%d", 73},
  {"Name=%ld, ", 74},
  {"Number=%ld, ", 75},
  {"String=%ld, ", 76},
  {"Literal=%ld, ", 77},
  {"Comment=%ld\n", 78},
  {"Files=%ld, ", 79},
  {"Tokens=%ld, ", 80},
  {"Bytes=%ld Kb, ", 81},
  {"Heap=%d+%d Kb, ", 82},
  {"Output=%ld (%ld tok, %ld hit)\n", 83},
  {", Freq=%ld/%ld=%.2f\n", 84},
  {"Sorting tokens...\n", 85},
  {"Writing `%s'...\n", 86},
  {"can't create `%s'", 87},
  {"level %d: %ld/%ld = %.0f%%\n", 88},
  {"\
Print all tokens found in a source file.\n\
  -i, --include=LANGS     include languages in LANGS (default: \"C C++ \
asm\")\n\
  -x, --exclude=LANGS     exclude languages in LANGS\n\
  -l, --lang-option=L:OPT pass OPT as a default for language L (see below)\n\
  -m, --lang-map=MAPFILE  use MAPFILE to map file names onto source \
language\n\
  -d, --default-lang=LANG make LANG the default source language\n\
  -p, --prune=NAMES       exclude the named files and/or directories\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n\
\n\
The following arguments apply to the language-specific scanners:\n", 89},
};

int _msg_tbl_length = 89;
