/* Automatically generated by po2tbl.sed from fileutils.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"^[yY]", 2},
  {"^[nN]", 3},
  {"group of %s changed to %s\n", 4},
  {"group of %s retained as %s\n", 5},
  {"can not change to null group", 6},
  {"invalid group name `%s'", 7},
  {"group number", 8},
  {"invalid group number `%s'", 9},
  {"you are not a member of group `%s'", 10},
  {"%s: invalid group number", 11},
  {"virtual memory exhausted", 12},
  {"Try `%s --help' for more information.\n", 13},
  {"Usage: %s [OPTION]... GROUP FILE...\n", 14},
  {"\
Change the group membership of each FILE to GROUP.\n\
\n\
  -c, --changes           like verbose but report only when a change is \
made\n\
  -h, --no-dereference    affect symbolic links instead of any referenced \
file\n\
                          (available only on systems with lchown system \
call)\n\
  -f, --silent, --quiet   suppress most error messages\n\
  -R, --recursive         change files and directories recursively\n\
  -v, --verbose           output a diagnostic for every file processed\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n", 15},
  {"\
\n\
Report bugs to fileutils-bugs@gnu.ai.mit.edu", 16},
  {"too few arguments", 17},
  {"--no-dereference (-h) is not supported on this system", 18},
  {"mode of %s changed to %04o (%s)\n", 19},
  {"mode of %s retained as %04o (%s)\n", 20},
  {"\
Usage: %s [OPTION]... MODE[,MODE]... FILE...\n\
  or:  %s [OPTION]... OCTAL_MODE FILE...\n", 21},
  {"\
\n\
  -c, --changes           like verbose but report only when a change is \
made\n\
  -f, --silent, --quiet   suppress most error messages\n\
  -v, --verbose           output a diagnostic for every file processed\n\
  -R, --recursive         change files and directories recursively\n\
      --help              display this help and exit\n\
      --version           output version information and exit\n\
\n\
Each MODE is one or more of the letters ugoa, one of the symbols +-= and\n\
one or more of the letters rwxXstugo.\n", 22},
  {"invalid mode", 23},
  {"owner of %s changed to ", 24},
  {"owner of %s retained as ", 25},
  {"\
Usage: %s [OPTION]... OWNER[.[GROUP]] FILE...\n\
  or:  %s [OPTION]... .[GROUP] FILE...\n", 26},
  {"\
Change the owner and/or group of each FILE to OWNER and/or GROUP.\n\
\n\
  -c, --changes          be verbose whenever change occurs\n\
  -h, --no-dereference   affect symbolic links instead of any referenced \
file\n\
                         (available only on systems with lchown system \
call)\n\
  -f, --silent, --quiet  suppress most error messages\n\
  -R, --recursive        operate on files and directories recursively\n\
  -v, --verbose          explain what is being done\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n\
\n\
Owner is unchanged if missing.  Group is unchanged if missing, but changed\n\
to login group if implied by a period.  A colon may replace the period.\n", 27},
  {"\
Usage: %s [OPTION]... SOURCE DEST\n\
  or:  %s [OPTION]... SOURCE... DIRECTORY\n", 28},
  {"\
Copy SOURCE to DEST, or multiple SOURCE(s) to DIRECTORY.\n\
\n\
  -a, --archive                same as -dpR\n\
  -b, --backup                 make backup before removal\n\
  -d, --no-dereference         preserve links\n\
  -f, --force                  remove existing destinations, never prompt\n\
  -i, --interactive            prompt before overwrite\n\
  -l, --link                   link files instead of copying\n\
  -p, --preserve               preserve file attributes if possible\n\
  -P, --parents                append source path to DIRECTORY\n\
  -r                           copy recursively, non-directories as files\n\
      --sparse=WHEN            control creation of sparse files\n\
  -R, --recursive              copy directories recursively\n\
  -s, --symbolic-link          make symbolic links instead of copying\n\
  -S, --suffix=SUFFIX          override the usual backup suffix\n\
  -u, --update                 copy only when the SOURCE file is newer\n\
                                 than the destination file or when the\n\
                                 destination file is missing\n\
  -v, --verbose                explain what is being done\n\
  -V, --version-control=WORD   override the usual version control\n\
  -x, --one-file-system        stay on this file system\n\
      --help                   display this help and exit\n\
      --version                output version information and exit\n\
\n\
By default, sparse SOURCE files are detected by a crude heuristic and the\n\
corresponding DEST file is made sparse as well.  That is the behavior\n\
selected by --sparse=auto.  Specify --sparse=always to create a sparse DEST\n\
file whenever the SOURCE file contains a long enough sequence of zero \
bytes.\n\
Use --sparse=never to inhibit creation of sparse files.\n\
\n", 29},
  {"\
The backup suffix is ~, unless set with SIMPLE_BACKUP_SUFFIX.  The\n\
version control may be set with VERSION_CONTROL, values are:\n\
\n\
  t, numbered     make numbered backups\n\
  nil, existing   numbered if numbered backups exist, simple otherwise\n\
  never, simple   always make simple backups\n", 30},
  {"\
\n\
As a special case, cp makes a backup of SOURCE when the force and backup\n\
options are given and SOURCE and DEST are the same name for an existing,\n\
regular file.\n", 31},
  {"sparse type", 32},
  {"symbolic links are not supported on this system", 33},
  {"cannot make both hard and symbolic links", 34},
  {"missing file arguments", 35},
  {"missing destination file", 36},
  {"when preserving paths, last argument must be a directory", 37},
  {"copying multiple files, but last argument (%s) is not a directory", 38},
  {"%s: omitting directory", 39},
  {"`%s' and `%s' are the same file", 40},
  {"%s: cannot overwrite directory with non-directory", 41},
  {"%s: overwrite `%s', overriding mode %04o? ", 42},
  {"%s: overwrite `%s'? ", 43},
  {"backing up `%s' would destroy source;  `%s' not copied", 44},
  {"cannot backup `%s'", 45},
  {"cannot remove old link to `%s'", 46},
  {"%s: cannot copy cyclic symbolic link", 47},
  {"cannot create directory `%s'", 48},
  {"%s: can make relative symbolic links only in current directory", 49},
  {"cannot create link `%s'", 50},
  {"cannot create fifo `%s'", 51},
  {"cannot create special file `%s'", 52},
  {"cannot read symbolic link `%s'", 53},
  {"cannot create symbolic link `%s'", 54},
  {"%s: unknown file type", 55},
  {"cannot un-backup `%s'", 56},
  {"cannot make directory `%s'", 57},
  {"`%s' exists but is not a directory", 58},
  {"cannot create regular file `%s'", 59},
  {"Usage: %s [OPTION]... [FILE]\n", 60},
  {"\
Output commands to set the LS_COLORS environment variable.\n\
\n\
Determine format of output:\n\
  -b, --sh, --bourne-shell    output Bourne shell code to set LS_COLORS\n\
  -c, --csh, --c-shell        output C shell code to set LS_COLORS\n\
  -p, --print-database        output defaults\n\
      --help                  display this help and exit\n\
      --version               output version information and exit\n\
\n\
If FILE is specified, read it to determine which colors to use for which\n\
file types and extensions.  Otherwise, a precompiled database is used.\n\
For details on the format of these files, run `dircolors --print-database'.\n", 61},
  {"%s:%lu: unrecognized keyword `%s'", 62},
  {"\
the options to output dircolors' internal database and\n\
to select a shell syntax are mutually exclusive", 63},
  {"\
no FILE arguments may be used with the option to output\n\
dircolors' internal database", 64},
  {"too many arguments", 65},
  {"no SHELL environment variable, and no shell type option given", 66},
  {"write error", 67},
  {"standard input", 68},
  {"%s is closed", 69},
  {"standard output", 70},
  {"unrecognized option `%s'", 71},
  {"invalid number `%s'", 72},
  {"unrecognized option `%s=%s'", 73},
  {"%s: invalid conversion", 74},
  {"\
only one conv in {ascii,ebcdic,ibm}, {lcase,ucase}, {block,unblock}, \
{unblock,sync}", 75},
  {"%u+%u records in\n", 76},
  {"%u+%u records out\n", 77},
  {"truncated record", 78},
  {"truncated records", 79},
  {"Usage: %s [OPTION]...\n", 80},
  {"\
Copy a file, converting and formatting according to the options.\n\
\n\
  bs=BYTES        force ibs=BYTES and obs=BYTES\n\
  cbs=BYTES       convert BYTES bytes at a time\n\
  conv=KEYWORDS   convert the file as per the comma separated keyword list\n\
  count=BLOCKS    copy only BLOCKS input blocks\n\
  ibs=BYTES       read BYTES bytes at a time\n\
  if=FILE         read from FILE instead of stdin\n\
  obs=BYTES       write BYTES bytes at a time\n\
  of=FILE         write to FILE instead of stdout, don't truncate file\n\
  seek=BLOCKS     skip BLOCKS obs-sized blocks at start of output\n\
  skip=BLOCKS     skip BLOCKS ibs-sized blocks at start of input\n\
      --help      display this help and exit\n\
      --version   output version information and exit\n\
\n\
BYTES may be suffixed: by xM for multiplication by M, by c for x1,\n\
by w for x2, by b for x512, by k for x1024.  Each KEYWORD may be:\n\
\n\
  ascii     from EBCDIC to ASCII\n\
  ebcdic    from ASCII to EBCDIC\n\
  ibm       from ASCII to alternated EBCDIC\n\
  block     pad newline-terminated records with spaces to cbs-size\n\
  unblock   replace trailing spaces in cbs-size records with newline\n\
  lcase     change upper case to lower case\n\
  ucase     change lower case to upper case\n\
  swab      swap every pair of input bytes\n\
  noerror   continue after read errors\n\
  sync      pad every input block with NULs to ibs-size\n", 81},
  {"Usage: %s [OPTION]... [FILE]...\n", 82},
  {"\
Show information about the filesystem on which each FILE resides,\n\
or all filesystems by default.\n\
\n\
  -a, --all             include filesystems having 0 blocks\n\
  -h, --human-readable  print sizes in human readable format (e.g., 1K 234M \
2G)\n\
  -i, --inodes          list inode information instead of block usage\n\
  -k, --kilobytes       use 1024-byte blocks, not 512 despite \
POSIXLY_CORRECT\n\
  -m, --megabytes       use 1024K-byte blocks, not 512 despite \
POSIXLY_CORRECT\n\
      --no-sync         do not invoke sync before getting usage info \
(default)\n\
  -P, --portability     use the POSIX output format\n\
      --sync            invoke sync before getting usage info\n\
  -t, --type=TYPE       limit listing to filesystems of type TYPE\n\
  -T, --print-type      print filesystem type\n\
  -x, --exclude-type=TYPE   limit listing to filesystems not of type TYPE\n\
  -v                    (ignored)\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n", 83},
  {"\
the option for counting 1MB blocks may not be used\n\
with the portable output format", 84},
  {"\
the option for printing with adaptive units may not be used\n\
with the portable output format", 85},
  {"file system type `%s' both selected and excluded", 86},
  {"cannot read table of mounted filesystems", 87},
  {"\
Summarize disk usage of each FILE, recursively for directories.\n\
\n\
  -a, --all             write counts for all files, not just directories\n\
  -b, --bytes           print size in bytes\n\
  -c, --total           produce a grand total\n\
  -D, --dereference-args  dereference PATHs when symbolic link\n\
  -h, --human-readable  print sizes in human readable format (e.g., 1K 234M \
2G)\n\
  -k, --kilobytes       use 1024-byte blocks, not 512 despite \
POSIXLY_CORRECT\n\
  -l, --count-links     count sizes many times if hard linked\n\
  -L, --dereference     dereference all symbolic links\n\
  -m, --megabytes       use 1024K-byte blocks, not 512 despite \
POSIXLY_CORRECT\n\
  -S, --separate-dirs   do not include size of subdirectories\n\
  -s, --summarize       display only a total for each argument\n\
  -x, --one-file-system  skip directories on different filesystems\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n", 88},
  {"cannot both summarize and show all entries", 89},
  {"current directory", 90},
  {"starting directory", 91},
  {"%ld\ttotal\n", 92},
  {"cannot change to directory %s", 93},
  {"cannot change to `..' from directory %s", 94},
  {"the strip option may not be used when installing a directory", 95},
  {"invalid mode `%s'", 96},
  {"`%s' is a directory", 97},
  {"`%s' is not a regular file", 98},
  {"fork system call failed", 99},
  {"cannot run strip", 100},
  {"invalid user `%s'", 101},
  {"invalid group `%s'", 102},
  {"\
Usage: %s [OPTION]... SOURCE DEST           (1st format)\n\
  or:  %s [OPTION]... SOURCE... DIRECTORY   (2nd format)\n\
  or:  %s -d [OPTION]... DIRECTORY...       (3rd format)\n", 103},
  {"\
In first two formats, copy SOURCE to DEST or multiple SOURCE(s) to\n\
DIRECTORY, while setting permission modes and owner/group.  In third\n\
format, make all components of the given DIRECTORY(ies).\n\
\n\
  -b, --backup        make backup before removal\n\
  -c                  (ignored)\n\
  -d, --directory     create [leading] directories, mandatory for 3rd \
format\n\
  -g, --group=GROUP   set group ownership, instead of process' current \
group\n\
  -m, --mode=MODE     set permission mode (as in chmod), instead of \
rw-r--r--\n\
  -o, --owner=OWNER   set ownership (super-user only)\n\
  -s, --strip         strip symbol tables, only for 1st and 2nd formats\n\
  -S, --suffix=SUFFIX override the usual backup suffix\n\
  -V, --version-control=WORD   override the usual version control\n\
      --help          display this help and exit\n\
      --version       output version information and exit\n\
\n", 104},
  {"%s: hard link not allowed for directory", 105},
  {"%s: cannot overwrite directory", 106},
  {"%s: replace `%s'? ", 107},
  {"%s: File exists", 108},
  {"cannot remove `%s'", 109},
  {"create %s %s to %s\n", 110},
  {"cannot create %s `%s' to `%s'", 111},
  {"\
Usage: %s [OPTION]... SOURCE [DEST]\n\
  or:  %s [OPTION]... SOURCE... DIRECTORY\n", 112},
  {"\
Link SOURCE to DEST (. by default), or multiple SOURCE(s) to DIRECTORY.\n\
Makes hard links by default, symbolic links with -s.\n\
\n\
  -b, --backup                 make backups for removed files\n\
  -d, -F, --directory          hard link directories (super-user only)\n\
  -f, --force                  remove existing destinations\n\
  -n, --no-dereference         treat destination that is a symlink to a\n\
                                 directory as if it were a normal file\n\
  -i, --interactive            prompt whether to remove destinations\n\
  -s, --symbolic               make symbolic links instead of hard links\n\
  -S, --suffix=SUFFIX          override the usual backup suffix\n\
  -v, --verbose                print name of each file before linking\n\
  -V, --version-control=WORD   override the usual version control\n\
      --help                   display this help and exit\n\
      --version                output version information and exit\n\
\n", 113},
  {"missing file argument", 114},
  {"symbolic link", 115},
  {"hard link", 116},
  {"link", 117},
  {"when making multiple links, last argument must be a directory", 118},
  {"ignoring invalid width in environment variable COLUMNS: %s", 119},
  {"ignoring invalid tab size in environment variable TABSIZE: %s", 120},
  {"invalid line width: %s", 121},
  {"invalid tab size: %s", 122},
  {"sort type", 123},
  {"time type", 124},
  {"format type", 125},
  {"colorization criterion", 126},
  {"unrecognized prefix: %s", 127},
  {"unparsable value for LS_COLORS environment variable", 128},
  {"\
List information about the FILEs (the current directory by default).\n\
Sort entries alphabetically if none of -cftuSUX nor --sort.\n\
\n\
  -a, --all                  do not hide entries starting with .\n\
  -A, --almost-all           do not list implied . and ..\n\
  -b, --escape               print octal escapes for nongraphic characters\n\
  -B, --ignore-backups       do not list implied entries ending with ~\n\
  -c                         sort by change time; with -l: show ctime\n\
  -C                         list entries by columns\n\
      --color[=WHEN]         control whether color is used to distinguish \
file\n\
                               types.  WHEN may be `never', `always', or \
`auto'\n\
  -d, --directory            list directory entries instead of contents\n\
  -D, --dired                generate output designed for Emacs' dired mode\n\
  -f                         do not sort, enable -aU, disable -lst\n\
  -F, --classify             append a character for typing each entry\n\
      --format=WORD          across -x, commas -m, horizontal -x, long -l,\n\
                               single-column -1, verbose -l, vertical -C\n\
      --full-time            list both full date and full time\n", 129},
  {"\
  -g                         (ignored)\n\
  -G, --no-group             inhibit display of group information\n\
  -i, --inode                print index number of each file\n\
  -I, --ignore=PATTERN       do not list implied entries matching shell \
PATTERN\n\
  -k, --kilobytes            use 1024 blocks, not 512 despite \
POSIXLY_CORRECT\n\
  -l                         use a long listing format\n\
  -L, --dereference          list entries pointed to by symbolic links\n\
  -m                         fill width with a comma separated list of \
entries\n\
  -n, --numeric-uid-gid      list numeric UIDs and GIDs instead of names\n\
  -N, --literal              print raw entry names (don't treat e.g. \
control\n\
                               characters specially)\n\
  -o                         use long listing format without group info\n\
  -p                         append a character for typing each entry\n\
  -q, --hide-control-chars   print ? instead of non graphic characters\n\
  -Q, --quote-name           enclose entry names in double quotes\n\
  -r, --reverse              reverse order while sorting\n\
  -R, --recursive            list subdirectories recursively\n\
  -s, --size                 print size of each file, in blocks\n", 130},
  {"\
  -S                         sort by file size\n\
      --sort=WORD            ctime -c, extension -X, none -U, size -S,\n\
                             status -c, time -t, atime -u, access -u, use \
-u\n\
      --time=WORD            show time as WORD instead of modification \
time:\n\
                             atime, access, use, ctime or status\n\
  -t                         sort by modification time; with -l: show mtime\n\
  -T, --tabsize=COLS         assume tab stops at each COLS instead of 8\n\
  -u                         sort by last access time; with -l: show atime\n\
  -U                         do not sort; list entries in directory order\n\
  -w, --width=COLS           assume screen width instead of current value\n\
  -x                         list entries by lines instead of by columns\n\
  -X                         sort alphabetically by entry extension\n\
  -1                         list one file per line\n\
      --help                 display this help and exit\n\
      --version              output version information and exit\n\
\n\
By default, color is not used to distinguish types of files.  That is\n\
equivalent to using --color=none.  Using the --color option without the\n\
optional WHEN argument is equivalent to using --color=always.  With\n\
--color=auto, color codes are output only if standard output is connected\n\
to a terminal (tty).\n", 131},
  {"Usage: %s [OPTION] DIRECTORY...\n", 132},
  {"\
Create the DIRECTORY(ies), if they do not already exist.\n\
\n\
  -m, --mode=MODE   set permission mode (as in chmod), not rwxrwxrwx - \
umask\n\
  -p, --parents     no error if existing, make parent directories as needed\n\
      --verbose     print a message for each created directory\n\
      --help        display this help and exit\n\
      --version     output version information and exit\n", 133},
  {"created directory `%s'", 134},
  {"Usage: %s [OPTION] NAME...\n", 135},
  {"\
Create named pipes (FIFOs) with the given NAMEs.\n\
\n\
  -m, --mode=MODE   set permission mode (as in chmod), not 0666 - umask\n\
      --help        display this help and exit\n\
      --version     output version information and exit\n", 136},
  {"fifo files not supported", 137},
  {"cannot make fifo `%s'", 138},
  {"Usage: %s [OPTION]... NAME TYPE [MAJOR MINOR]\n", 139},
  {"\
Create the special file NAME of the given TYPE.\n\
\n\
  -m, --mode=MODE   set permission mode (as in chmod), not 0666 - umask\n\
      --help        display this help and exit\n\
      --version     output version information and exit\n\
\n\
MAJOR MINOR are forbidden for TYPE p, mandatory otherwise.  TYPE may be:\n\
\n\
  b      create a block (buffered) special file\n\
  c, u   create a character (unbuffered) special file\n\
  p      create a FIFO\n", 140},
  {"wrong number of arguments", 141},
  {"block special files not supported", 142},
  {"\
when creating block special files, major and minor device\n\
numbers must be specified", 143},
  {"invalid major device number `%s'", 144},
  {"invalid minor device number `%s'", 145},
  {"character special files not supported", 146},
  {"\
when creating character special files, major and minor device\n\
numbers must be specified", 147},
  {"major and minor device numbers may not be specified for fifo files", 148},
  {"cannot move `%s' across filesystems: Not a regular file", 149},
  {"%s: replace `%s', overriding mode %04o? ", 150},
  {"cannot move `%s' to `%s'", 151},
  {"\
Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY.\n\
\n\
  -b, --backup                 make backup before removal\n\
  -f, --force                  remove existing destinations, never prompt\n\
  -i, --interactive            prompt before overwrite\n\
  -S, --suffix=SUFFIX          override the usual backup suffix\n\
  -u, --update                 move only older or brand new files\n\
  -v, --verbose                explain what is being done\n\
  -V, --version-control=WORD   override the usual version control\n\
      --help                   display this help and exit\n\
      --version                output version information and exit\n\
\n", 152},
  {"when moving multiple files, last argument must be a directory", 153},
  {"Usage: %s [OPTION]... EXISTING_DIR NEW_DIR\n", 154},
  {"\
Rename EXISTING_DIR to NEW_DIR.\n\
\n\
   --help      display this help and exit\n\
   --version   output version information and exit\n", 155},
  {"cannot get current directory", 156},
  {"cannot rename `.' or `..'", 157},
  {"`%s' is not a directory", 158},
  {"cannot write to `%s'", 159},
  {"`%s' is an ancestor of `%s'", 160},
  {"cannot link `%s' to `%s'", 161},
  {"cannot unlink `%s'", 162},
  {"cannot remove `.' or `..'", 163},
  {"%s: remove %s`%s', overriding mode %04o? ", 164},
  {"directory ", 165},
  {"%s: remove %s`%s'? ", 166},
  {"%s: is a directory", 167},
  {"%s: descend directory `%s', overriding mode %04o? ", 168},
  {"%s: descend directory `%s'? ", 169},
  {"%s: remove directory `%s' (might be nonempty)? ", 170},
  {"%s: remove directory `%s'? ", 171},
  {"\
%s: WARNING: Circular directory structure.\n\
This almost certainly means that you have a corrupted file system.\n\
NOTIFY YOUR SYSTEM MANAGER.\n\
Cycle detected:\n\
%s\n\
is the same file as\n", 172},
  {"%s: continue? ", 173},
  {"Usage: %s [OPTION]... FILE...\n", 174},
  {"\
Remove (unlink) the FILE(s).\n\
\n\
  -d, --directory       unlink directory, even if non-empty (super-user \
only)\n\
  -f, --force           ignore nonexistent files, never prompt\n\
  -i, --interactive     prompt before any removal\n\
  -r, -R, --recursive   remove the contents of directories recursively\n\
  -v, --verbose         explain what is being done\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n", 175},
  {"Usage: %s [OPTION]... DIRECTORY...\n", 176},
  {"\
Remove the DIRECTORY(ies), if they are empty.\n\
\n\
  -p, --parents   remove explicit parent directories if being emptied\n\
      --help      display this help and exit\n\
      --version   output version information and exit\n", 177},
  {"Usage: %s [OPTION]\n", 178},
  {"\
Force changed blocks to disk, update the super block.\n\
\n\
  --help      display this help and exit\n\
  --version   output version information and exit\n", 179},
  {"ignoring all arguments", 180},
  {"\
Update the access and modification times of each FILE to the current time.\n\
\n\
  -a                     change only the access time\n\
  -c                     do not create any files\n\
  -d, --date=STRING      parse STRING and use it instead of current time\n\
  -f                     (ignored)\n\
  -m                     change only the modification time\n\
  -r, --reference=FILE   use this file's times instead of current time\n\
  -t STAMP               use MMDDhhmm[[CC]YY][.ss] instead of current time\n\
      --time=WORD        access -a, atime -a, mtime -m, modify -m, use -a\n\
      --help             display this help and exit\n\
      --version          output version information and exit\n\
\n\
STAMP may be used without -t if none of -drt, nor --, are used.\n", 181},
  {"invalid date format `%s'", 182},
  {"time selector", 183},
  {"cannot specify times from more than one source", 184},
  {"file arguments missing", 185},
};

int _msg_tbl_length = 185;
